package transport

import (
	"context"
	"net/url"

	// init encoding
	_ "github.com/go-kratos/kratos/v2/encoding/json"
	_ "github.com/go-kratos/kratos/v2/encoding/proto"
	_ "github.com/go-kratos/kratos/v2/encoding/xml"
	_ "github.com/go-kratos/kratos/v2/encoding/yaml"
)

// Server is transport server.
// 一个服务只有启动和关闭操作
type Server interface {
	Start(context.Context) error
	Stop(context.Context) error
}

// Endpointer is registry endpoint.
type Endpointer interface {
	Endpoint() (*url.URL, error)
}

// Header is the storage medium used by a Header.
type Header interface {
	Get(key string) string
	Set(key string, value string)
	Keys() []string
}

// Transporter is transport context value interface.
// 传输层上下文接口, 封装挺优雅的
type Transporter interface {
	// grpc
	// http
	// 类型
	Kind() Kind
	// Server Transport: grpc://127.0.0.1:9000
	// Client Transport: discovery:///provider-demo
	// 两种类型
	Endpoint() string
	// Service full method selector generated by protobuf
	// example: /helloworld.Greeter/SayHello
	Operation() string
	// http: http.Header
	// grpc: metadata.MD
	Header() Header
}

// Kind defines the type of Transport
type Kind string

func (k Kind) String() string {
	return string(k)
}

// Defines a set of transport kind
const (
	KindGRPC Kind = "grpc"
	KindHTTP Kind = "http"
)

type serverTransportKey struct{}
type clientTransportKey struct{}

// 标准库命名方式，带有context,放在第一个参数位置，函数名后面也带有Context
// NewServerContext returns a new Context that carries value.
func NewServerContext(ctx context.Context, tr Transporter) context.Context {
	return context.WithValue(ctx, serverTransportKey{}, tr)
}

// FromServerContext returns the Transport value stored in ctx, if any.
func FromServerContext(ctx context.Context) (tr Transporter, ok bool) {
	tr, ok = ctx.Value(serverTransportKey{}).(Transporter)
	return
}

// NewClientContext returns a new Context that carries value.
func NewClientContext(ctx context.Context, tr Transporter) context.Context {
	return context.WithValue(ctx, clientTransportKey{}, tr)
}

// FromClientContext returns the Transport value stored in ctx, if any.
func FromClientContext(ctx context.Context) (tr Transporter, ok bool) {
	tr, ok = ctx.Value(clientTransportKey{}).(Transporter)
	return
}
